logging:
  level:
    com.axway.apim: INFO
axway:
  apim:
    connecttimeout: 30000
    readtimeout: 30000
spring:
  security:
    user:
      name: admin
      password: changeme
  cloud:
    openservicebroker:
      catalog:
        services:
        - id: ED01F448-40C7-4A9D-93D0-51E7D4E93CA1
          name: Axway-APIM
          description: Axway APIM Service Broker Implementation
          bindable: true
          tags:
          - Axway
          - API
          - API Management
          - API Platform
          - API Gateway
          - Axway AMPLIFY
          metadata:
            displayName: Axway Amplify APIM
            imageUrl: https://cdn.axway.com/globalnav/axway-logo-top.svg
            longDescription: Axway Amplify APIM Service Broker
            providerDisplayName: Axway
            documentationUrl: https://github.com/Axway-API-Management-Plus
            supportUrl: https://github.com/Axway-API-Management-Plus
          plans:
          - id: 1A6C15A6-1DE1-4870-A4F2-EA0A905F4A0F
            name: APIM-Free
            description: This is a default Axway plan.  All services are created equally.
            metadata:
              displayName: Standard
              longDescription: Standard Plan
              bullets:  Routing, Authentication, Throtlling
              costs:
              -
                amount:
                  usd: 0.0
                unit: MONTHLY
            free: false
          - id: 2A6C15A6-1DE1-4870-A4F2-EA0A905F4A0F
            name: APIM-Premium
            description: This is a Paid Axway Premium plan.  All services are created equally.
            metadata:
              displayName: Premium
              longDescription: Premium Plan
              bullets: 
              - Routing
              - Authentication
              - Throtlling
            free: false